### ISSUE TITLE
Parent is required when editing in Netlify CMS

### ISSUE THREAD

**Issue by zairja** [broeker/spacebook#14]
**Describe the bug**
When trying to publish a page with top-level navigation, the parent field is required when publishing via Netlify CMS, preventing it from getting published/saved.

**To Reproduce**
1. While logged into the Netlify CMS, edit a top-level page or create a new page that will not have a parent.
2. Click on the 'Publish' button in the top-right corner.
4. See input validation that a parent is required, preventing the page from being published.

**Expected behavior**
The parent field should be optional. When no parent is provided, the eleventyNavigation parent property should not be present at all in the .md file (this is the case with existing top-level pages like "Getting Started").

**Screenshots**
![image](https://user-images.githubusercontent.com/5422143/102671978-740d8200-4155-11eb-8120-c256e54ca438.png)

I can attempt a fix and create a PR if this is not a priority since it is a big hassle with some of my current projects. Thank you for your work!

**Comment by broeker** [comment]
Awesome thanks for catching -- this should new be fixed in main branch, feel free to re-open if not.
