### ISSUE TITLE
EmbedEverything plugin does not work for Instagram

### ISSUE THREAD

**Issue by zairja** [broeker/spacebook#15]
**Describe the bug**
Putting an Instagram URL on its own line in markdown does not embed it.

**To Reproduce**
1. Paste the URL into the markdown file.
2. The URL is rendered as a link instead of an embedded image/link.

**Expected behavior**
The current markdown rendering seems to take any URL (even if the http / www is omitted) and wrap it in an `<a>` tag whereas embed-everything requires the Instagram URL to be by itself wrapped in `<p>` tags. It may not be something that can be fixed / tweaked if it's core to 11ty.

**Comment by broeker** [comment]
@zairja interesting, I had not tested Instagram but on my local copy it seems to be working okay:

`https://www.instagram.com/p/Btg1jd_HJsT/`

Inserting that on its own line resulted in the attached screenshot. I'll leave this open pending further details.

![insta](https://user-images.githubusercontent.com/30089460/102677411-e38c6d00-4167-11eb-9d14-f1e59353a5b4.png)

**Comment by broeker** [comment]
I do notice a small delay where it renders a small gray bar before rendering the insta post, but not sure I'll have any control over that. I also fixed the CSS to make sure Insta embeds are centered like other images/embeds.

**Comment by zairja** [comment]
I somehow borked a fork. Unable to trace down where the issue cropped up. Confirmed it works fine with latest changes in spacebook repo.

sidenote: unfortunately deploying directly to netlify (letting it create the github repo) doesn't flag created repos as forks making it difficult to merge in upstream changes 😢. going forward, I'll fork then connect the repo to netlify.
