### ISSUE TITLE
Link to markdown tags returns 404

### ISSUE THREAD

**Issue by enmcewan** [broeker/spacebook#23]
**Describe the bug**
The documentation page https://spacebook.app/getting-started/content/#adding-your-content has the paragraph starting "Your content can include all sorts of markdown tags..." with a link to https://spacebook.app/markdown but this returns a 404 error.

**Comment by broeker** [comment]
Fixed, thank you!

**Comment by PipeItToDevNull** [comment]
this is a 404 again
