### ISSUE TITLE
Change Tailwind CSS

### ISSUE THREAD

**Issue by enmcewan** [broeker/spacebook#24]
I was trying to fix a problem with the style for the navigation links: In dark mode on hover, they are too dark to see.

![image](https://user-images.githubusercontent.com/28487893/105610741-c0606900-5d76-11eb-82f8-7e2cdddbb408.png)

I found a rule in styles/tailwind.css and applied a change:

```
  nav ul li a:hover {
    @apply text-gray-900 dark:text-gray-100;
  }
```

But it's not applied after running npm start. In fact, I can delete the file and it doesn't matter.

So, how can I update the CSS?

**Comment by broeker** [comment]
Hi @enmcewan thanks for catching this -- I have pushed a fix to main for this:

```
  nav ul li a:hover {
    @apply text-gray-900 dark:text-gray-400;
  }
```

On my end I was able to see this change via hot reload, so not sure what is going on with your build but it sounds like the _tmp/style.css is not getting "watched" correctly. Did you run `npm run build` after running your first `npm install`?

**Comment by enmcewan** [comment]
Hi @broeker, no problem. Thanks for building this!

I thought I ran ```npm run build``` initially, but I later ran it again (trying to see if that fixed the other issues) and was getting errors.

As suspected, it's because I'm on **Windows** .To get the ```build``` script running, I installed the ```cross-env``` package and changed the script to:
```
"build": "cross-env NODE_ENV=production=true eleventy && cross-env NODE_ENV=production postcss styles/tailwind.css --o _site/style.css && cross-env ./node_modules/.bin/cleancss -o _site/style.css _site/style.css",
```
I've done that before for other eleventy sites. The build script runs now.

I tried a fresh install of spacebook and with cross-env, updated the script and ran```npm run build```.
But still, any changes to Tailwind are not updated. In fact, ```_tmp\style.css``` is never updated with build or start.
I'm thinking there must be another setting somewhere that is ignored on Windows, but there's no errors. Any clues where to look?

**Comment by broeker** [comment]
Interesting. Have you tested other eleventy projects? 

The way I have the css watch set up mirrors this starter:

https://github.com/gregwolanski/eleventy-tailwindcss-alpinejs-starter

So I'd be curious if you have similar issues on that project or if it is something specfic to mine.I don't have a Windows machine to test but  there seem to have been numerous issues (most closed) in the eleventy issue queue for hot reload problems in Windows, perhaps something in here might help?

https://github.com/11ty/eleventy/issues/701

If you ever do get a working Windows install I'd be interested in adding any changes to my documentation!

**Comment by enmcewan** [comment]
OK, the issue is that I'm running VS Code integrated terminal in Cmd/Node mode. With that, the '& or &&' operator is ignored on the npm scripts. E.g. :
```
"start": "eleventy --serve & postcss styles/tailwind.css --o _tmp/style.css --watch"
```
Here only ```eleventy --serve``` runs and the ```postcss``` command is ignored.

One solution in this case (Using Cmd/Node Terminal) is another way to run multiple commands. Install  ```npm-run-all``` and then adding new scripts like below:

```
    "postcss": "postcss styles/tailwind.css --o _tmp/style.css --watch",
    "eleventy": "eleventy --serve",
    "start2": "npm-run-all --parallel postcss eleventy",
```
Run ```start2``` from the Cmd/Node Terminal and everything works. Note that a similar change is required for the ```"build"``` script.

Another, and simpler solution, is with Git installed, you can run the terminal in "bash" mode then the npm scripts run out-of-the-box. You can also run Git Bash independently of VS Code.

**Comment by enmcewan** [comment]
Ha! I was in the middle of my reply when yours came in. I actually ran through eleventy-tailwindcss-alpinejs-starter as a sanity check and had the same issue. Finally I recalled an eleventy project from last year I did and used the ```npm-run-all``` solution.
Subsequently I have started using Git and figured out that Git Bash runs everything out of the box. Deduced that after reading [this article](https://itnext.io/4-solutions-to-run-multiple-node-js-or-npm-commands-simultaneously-9edaa6215a93).

I hope my previously reply is enough for you to update your documentation. If you need anything else, just let me know.

**Comment by broeker** [comment]
Nicely done, and thanks for leaving so much info for the next Windows user who stumbles across these issues 🤠
