### ISSUE TITLE
A couple more Dark Mode Styling Issues

### ISSUE THREAD

**Issue by enmcewan** [broeker/spacebook#25]
### Footer Nav Links
The footer nav links are not visible on hover:

![image](https://user-images.githubusercontent.com/28487893/105640826-c709e180-5e45-11eb-873a-a1551cec7f53.png)

I fixed these with a new rule in tailwind.css:
```
 .prose .footer-nav a:hover {
    @apply dark:text-pink-200 !important
  }
```

### Search Box Input Text
The search text is not visible when typing:

![image](https://user-images.githubusercontent.com/28487893/105640892-6333e880-5e46-11eb-811f-abc6dcfbe0ff.png)

I fixed these with a new rule in tailwind.css:
```
 input {
    @apply dark:text-gray-300
  }
```

**Comment by broeker** [comment]
Excellent, thanks for catching these @enmcewan , you are officially Vice President of Dark Mode. Fixes for both have been pushed to main branch. 👍

**Comment by enmcewan** [comment]
> Excellent, thanks for catching these @enmcewan, you are officially Vice President of Dark Mode. Fixes for both have been pushed to main branch. 👍

Excellent, nothing like starting the week with a promotion.
